### ISSUE TITLE
get update name of BO 

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bacnet-server-c#1]
same as we can update the  `PROP_PRESENT_VALUE`
https://github.com/bacnet-stack/bacnet-stack/blob/ba0cbc1fb8768ff7b915904d836bd29ba32ed64b/src/bacnet/basic/object/bo.c#L365
we want to be able to update this name aswell `PROP_OBJECT_NAME` 
https://github.com/bacnet-stack/bacnet-stack/blob/ba0cbc1fb8768ff7b915904d836bd29ba32ed64b/src/bacnet/basic/object/bo.c#L434

see example of being able to write a string to update the bacnet sever name

start a new server with device-id `2508`

```
cd bacnet-stack-bacnet-stack-1.0.0/bin
./bacserv 2508
```

read the server name
```
./bacrp 2508 8 2508 77
```
write the server name
```
./bacwp 2508 8 2508 77 0 -1 7 test2
```

read the point name
```
./bacrp 2508 4 1 77
```
write the server name `see the error  `BACnet Error: property: write-access-denied`
```
aidan@aidan-ThinkPad-T480:~/code/bacnet-stack-bacnet-stack-1.0.0/bin$ ./bacwp 2508 4 1 77 0 -1 7 new-bo-name
BACnet Error: property: write-access-denied
aidan@aidan-ThinkPad-T480:~/code/bacnet-stack-bacnet-stack-1.0.0/bin$ 
```

**Comment by shomaglasang** [comment]
Taking on this @NubeDev . Thanks

**Comment by shomaglasang** [comment]
@NubeDev  do I need some permissions to update/resolve the ticket?

**Comment by shomaglasang** [comment]
@NubeDev here's the updated bo.c file. Just unzip and drop on src/bacnet/basic/object/bo.c.
[bo.zip](https://github.com/NubeIO/bacnet-server-c/files/8732062/bo.zip)

**Comment by shomaglasang** [comment]
Will mark this as completed @NubeDev .
Ready for the next one.
