### ISSUE TITLE
Rounding the write value

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bacnet-server-c#14]
when i write `23.44` it returns 23
```
pi@raspberrypi:~/bacnet-stack-bacnet-stack-1.0.0/bin $ ./bacwp 1234 1 1 85 16 -1 4 23.44

WriteProperty Acknowledged!
pi@raspberrypi:~/bacnet-stack-bacnet-stack-1.0.0/bin $ ./bacrp 1234 1 1 87
{Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,23.000000}

```

**Comment by NubeDev** [comment]
@shomaglasang can you please also check the AV and AI as they might be the same

**Comment by shomaglasang** [comment]
@NubeDev mate the current implementation of AV and AI  do not support the PROP_PRIORITY_ARRAY property. Only AO supports PROP_PRIORITY_ARRAY property. Do you think AV and AI should also support PROP_PRIORITY_ARRAY?
