### ISSUE TITLE
What to publish on change

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bacnet-server-c#5]
When to publish data over MQTT 

The BV, BO, AO and AVs

#### PROP_PRIORITY_ARRAY
https://github.com/NubeIO/bacnet-server-c/blob/e3f3314c55b75cc596027c405914160a4a699f7a/bacnet-stack/src/bacnet/basic/object/bo.c#L298

#### PROP_RELINQUISH_DEFAULT
https://github.com/NubeIO/bacnet-server-c/blob/e3f3314c55b75cc596027c405914160a4a699f7a/bacnet-stack/src/bacnet/basic/object/bo.c#L350

**Comment by shomaglasang** [comment]
@NubeDev mate, can you test BO? It now publish like this:
```
bacnet/bo/0/pri: {Null,Null,0,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null,1}
```
Also for PROP_RELINQUISH_DEFAULT:
```
bacnet/bo/0/rel: 1
```

**Comment by shomaglasang** [comment]
@NubeDev hey mate, already supported publishing on changes to to BV and AO PROP_PRIORITY_ARRAY and PROP_RELINQUISH_DEFAULT. Please test if you can.

I don't think this will apply to AV. The current implementation of AV in https://github.com/NubeIO/bacnet-server-c/blob/master/bacnet-stack/src/bacnet/basic/object/av.c does not use priority array and relinquish default in any of the functions. I checked the main repo but didn't find any information if the implementation/specs is still on-development.

**Comment by shomaglasang** [comment]
PROP_PRORITY_ARRAY already supported in AV.
Closing this mate @NubeDev
