### ISSUE TITLE
make units none

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bacnet-server-c#7]
https://github.com/NubeIO/bacnet-server-c/blob/10a79451d0084a76e9c5aefedd6758505bbe0e9d/bacnet-stack/src/bacnet/basic/object/ao.c#L372

make uints `none` for `AO, AV, and AI`

**Comment by shomaglasang** [comment]
@NubeDev changed the default property unit to "no-units".
AO
```
./bin/bacrp 1234 1 1 117   --mac 10.104.0.11:47808
no-units
```

AV
```
./bin/bacrp 1234 2 1 117   --mac 10.104.0.11:47808
no-units
```

AI
```
./bin/bacrp 1234 0 1 117   --mac 10.104.0.11:47808
no-units
```

**Comment by shomaglasang** [comment]
Default property unit for AO, AI and AV is "no-units".
