### ISSUE TITLE
On start of stack send MQTT  

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bacnet-server-c#9]
send a message so the MQTT client know the stack just restarted

**Comment by shomaglasang** [comment]
@NubeDev  can you give me the format of the topic?

**Comment by shomaglasang** [comment]
@NubeDev mate, I set the topic format to this and the value is "started".
```
bacnet/program/object_instance_number/state
```
Example:
```
bacnet/program/1234/state: started
```

**Comment by shomaglasang** [comment]
Already supported mate @NubeDev . Please re-open if you want to change the current implementation.
